          services:
            db:
              image: postgres
              environment:
                POSTGRES_PASSWORD: postgres
              ports:
                - "5432:5432"
              volumes:
                - db-data:/var/lib/postgresql/data
            pgadmin:
              image: dpage/pgadmin4
              restart: always
              environment:
                PGADMIN_DEFAULT_EMAIL: claire.graham@students.opit.com
                PGADMIN_DEFAULT_PASSWORD: root
              ports:
                - "5050:80"
          volumes:
            db-data:
